name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Add Clever Cloud repository
        run: git remote add clever git+ssh://git@push-par-clevercloud-customers.services.clever-cloud.com/${{ secrets.CLEVER_APP_ID }}.git
      - name: Push to Clever Cloud
        run: git push clever main:master
